---
- name: newcanonical
  shell: postmap /etc/postfix/canonical
  notify: restart postfix

- name: newaliases
  shell: newaliases
  notify: restart postfix

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart snmpd
  service:
    name: snmpd
    state: restarted

...