---
- block:
  - name: install packages for mail setup
    yum:
      name: "{{ osbasic_snmpd_packages }}"
      state: present

  - name: enable snmpd
    service:
      name: snmpd
      enabled: yes
      
  - name: create snmpd.conf
    template:
      src: snmpd.conf.j2
      dest: /etc/snmp/snmpd.conf
    notify: restart snmpd
      
  - name: uniqconsulting.firewall
    include_role:
      name: uniqconsulting.firewall
    vars:
      firewall_open_ports:
      - port: 161
        protocol: udp
      - port: 162
        protocol: udp
    
  when: osbasic_snmpd
...
